module.exports = ['Beverage Dissemination Officer',
'Digital Overlord',
'Retail Jedi',
'Wizard of Light Bulb Moments',
'Chief Chatter',
'Animal Colourist',
'Problem Wrangler',
'Bender of all things Balloons',
'Digital Dynamo',
'Direct Mail Demi-God',
'Dream Alchemist',
'Marketing Rockstar',
'Light Bender',
'Space Travel Agent',
'Associate to the Executive Manager of Marketeering and Conservation efforts',
'Pneumatic device and machine optimizer',
'Senior Kindle Evangelist',
'Brand Evangelist',
'Chief Inspiration Officer',
'Part-Time Czar',
'Associate Vice President',
'Patron Saint of Academic Studying',
'Personalized care assistant',
'Hair Boiler',
'Cheese Sprayer',
'Oyster Floater',
'Marketing Rockstar',
'Grand Master of Underlings',
'Creativity Analyst',
'Sales Ninja',
'Conversation Architect',
'Director of Fun',
'New Media Guru',
'Initiative Officer',
'Social Media Trailblazer',
'Corporate Magician',
'Master Handshaker',
'Communications Ambassador',
'Happiness Advocate',
'Under Secretary to the Sub-Committee',
'Hyphenated-specialist',
'Second Tier Helpdesk Analyst',
'Actions and Repercussions Adviser',
'Professionalist International and world-wide optical and vision-focused tenured professorship',
'Creator of Happiness',
'Change Magician',
'Chief Biscuit Dunker'];
