module.exports = ['The Priestess of Justice',
'The Maid of Dreams',
'The Keeper of Spark',
'The Bard of Shadow',
'The Mage of Hope ',
'The Rogue of Twilight',
'The Thief of Crystal',
'The Prince of Void',
'The Heir of Pain',
'The Mage of Mist ',
'The Heir of Mystery',
'The Warrior of Spark',
'The Lady of Tune',
'The Bard of Ink',
'The Witch of Metal ',
'The Princess of Day',
'The Mage of Light',
'The Wizard of Spark',
'The Priestess of Lightning',
'The Maid of Time ',
'The Seer of Stars',
'The Thief of Ice',
'The Mage of Ink',
'The Keeper of Darkness',
'The Princess of Flames ',
'The Fool of Heart',
'The Keeper of Shadow',
'The Guardian of Spark',
'The Heir of Dreams',
'The King of Breath ',
'The Witch of Twilight',
'The Maid of Stars',
'The Bard of Mist',
'The Lord of Night',
'The Knight of Ice ',
'The Priest of Spirit',
'The Princess of Heart',
'The Warrior of Day',
'The Guardian of Fear',
'The Heir of Life ',
'The Lord of Dawn',
'The Bard of Heart',
'The Warrior of Day',
'The Lady of Tears',
'The Witch of Spark ',
'The Seer of Twilight',
'The Lord of Death',
'The Rogue of Night',
'The Page of Time',
'The Wizard of Spirit ',
'The Queen of Aether',
'The Bard of Earth',
'The Page of Blood',
'The Princess of Birth',
'The Mage of Day ',
'The Priestess of Heart',
'The Priest of Tune',
'The Keeper of Flames',
'The Heir of Sound',
'The Warrior of Beauty '];
